name: Vib PR

on:
  push:
    tags:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: deps
      run: sudo apt-get install -y mtools xorriso git libconfuse-dev podman buildah slirp4netns uidmap containers-storage

    - name: genimage
      run: |
        mkdir deps-build
        curl -SLO https://github.com/pengutronix/genimage/releases/download/v18/genimage-18.tar.xz
        tar -xvf genimage-18.tar.xz -C deps-build/
        cd deps-build/genimage-18/
        ./configure --prefix=/usr
        sudo make install


    - uses: vanilla-os/vib-gh-action@v0.8.1
      with:
        recipe: 'recipe.yml'

    - name: Build the Docker image
      run: |
        sudo chmod 777 plugins/*
        sudo ls -al plugins/
        sudo su -c "./vib compile --runtime podman"
        sudo chmod 777 genimg/build/vanilla_installer.iso

    - name: generate checksums
      run: |
        cd genimg/build
        sha512sum vanilla_installer.iso > ../../vanilla_installer.iso.DIGESTS
        sha256sum vanilla_installer.iso > ../../vanilla_installer.iso.DIGESTS
        md5sum vanilla_installer.iso >> ../../vanilla_installer.iso.DIGESTS

    - name: Upload iso
      if: github.repository == 'Vanilla-OS/installer-image'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          genimg/build/vanilla_installer.iso

    - name: Attest generated files
      if: github.repository == 'Vanilla-OS/installer-image'
      id: attest
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'genimg/build/vanilla_installer.iso'
